version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=casinodb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/casinodb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - STRIPE_API_KEY=sk_test_51RGeOjPsNS1uIdSUCXQxfhkxuynIR7mXl3ANwYU4nD5Uo6LyNwAu5sk1FqiThSfAhODCPyyC6epwC48ozcMs3Dse00OiQTBLjy
      - STRIPE_WEBHOOK_SECRET=whsec_YOUR_WEBHOOK_SECRET
      - STRIPE_PUBLISHABLE_KEY=pk_test_51RGeOjPsNS1uIdSU80veezvYOkfGhCObUFHhQGmMJgDtljPRtMpflSTatTKF10VEIHeNS0LqbJCBtL4WDFRgRDTY00mnSEp14e
      - STRIPE_CURRENCY=eur
      - STRIPE_CREDIT_MULTIPLIER=1000
      - JWT_EXPIRATION=86400000
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:8080
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: 