# Usa la última imagen de PostgreSQL
FROM postgres:latest

# Configurar las variables de entorno
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin123
ENV POSTGRES_DB=casinodb

# Exponer el puerto de PostgreSQL
EXPOSE 5432


CMD ["postgres"]
